### ISSUE TITLE
Bold text in Bard content field does not become light in widget when dark mode is active.

### ISSUE THREAD

**Issue by helloDanuk** [mitydigital/statamic-sticky-notes#1]
In dark mode, bold text in the widget remains dark.

<img width="175" alt="Bildschirmfoto 2024-06-04 um 11 10 34" src="https://github.com/mitydigital/statamic-sticky-notes/assets/8265902/8ab2055b-c557-47b2-a13f-da2709e54221">

**Comment by martyf** [comment]
This has been resolved with 1.0.1.

Thanks for the report!
